site_name: Galaxy Tool Dev
pages:
- [index.md, Home]
- [01_Introduction.md, Introduction]
- [02_SDK.md, Galaxy SDK]
- [03_ToolDev.md, Tool Development]
- [04_ToolWrapper.md, Tool Wrapper Syntax]
- [05_Docker.md, Docker]
- [06_Glossary.md, Glossary]
