site_name: Galaxy Tool Dev
pages:
- [index.md, Creating Galaxy tools and workflows]
- [01_GCE.md, Introduction, Google Cloud Engine]
- [01_Vagrant.md, Introduction, Vagrant]
- [02_Examples.md, Introduction, Working With Examples]
- [03_Docker.md, Development, Docker]
- [04_ToolWrapper.md, Development, Tool Wrapper Syntax]
- [05_ToolDev.md, Development, Tool Development]
- [06_Submitting.md, Submitting, Submitting Code]
- [07_FAQ.md, Help, FAQ]
- [07_Glossary.md, Help, Glossary]
imports:
-
    file: planemo/docs/commands/docker_build.rst
    name: PLANEMO_DOCKER
    head_trim: 6
-
    file: planemo/docs/_writing_parameters.rst
    name: WRITING_PARAMS
    head_trim: 6
templates:
- 03_Docker.md
- 05_ToolDev.md
